#!/usr/bin/perl
use strict;
use warnings;
use feature 'say';
say "enter your name:";  #in place of print we can use say also 
#if we want to print two names if we use say no need to use \n to print the another on next line
#directly by using the say the two names will display in different lines
my $name=<STDIN>;   #standard input - STDIN
chomp($name); #is used to remove the \n
my $vars = ("hello " . $name);
say "$vars";
#performing addition
say "first number:";
my $num1=<STDIN>;
chomp($num1);
say "second number:";
my $num2=<STDIN>;
chomp($num2);
my $sum = $num1 + $num2;
say "the sum is: $sum";
#say "the multiplelines(print stop to finish)"
# to execute the next subtraction operation the say command should be commented because the stop condition is written inside the say command

#performing subtraction
say "first number1:";
my $num3=<STDIN>;
chomp($num3);
say "second number1:";
my $num4=<STDIN>;
chomp($num4);
my $diff = $num3 - $num4;
say "the difference is: $diff";
say "the multiplelines(print stop to finish)"
